### ISSUE TITLE
code can not run successfully

### ISSUE THREAD

**Issue by 0814zm** [summitgao/SIC_SPBL#1]
Hello,Mr. Gao.
  I have a problem when I run your project code.It tells me that it can't read the SeaIceDataset.mat.I can't find this file in your folder.Please help me about this problem.Thank you!
![image](https://user-images.githubusercontent.com/82143211/157356663-f8c5db0e-a2f8-4fde-9ec1-e48afd69cb78.png)

**Comment by summitgao** [comment]
非常抱歉。。。刚找了找，过去好几年，这个数据我已经找不到了 

推荐你换一个数据集，Indian Pines, Pavia 都是可以的
